version: '3'
services:

  server:
    build: .
    container_name: backcourses-app
    ports:
    - "8000:8000"
    command: sh -c "cd /back_courses
             && alembic upgrade head
             && python main.py"
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    container_name: backcourses-db
    env_file:
      - .env